=== rlawjddbs/jsp_prj/WebContent/xml0327/computer.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT computers (computer)*>
<!ELEMENT computer (cpu+, mb?, ram+, ps+, (hdd? | ssd?), odd?, vga?)>
<!ELEMENT cpu (#PCDATA)> 
<!ELEMENT mb (#PCDATA)> 
<!ELEMENT ram (#PCDATA)> 
<!ELEMENT ps (#PCDATA)>
<!ELEMENT hdd (#PCDATA)> 
<!ELEMENT ssd (#PCDATA)>
<!ELEMENT odd (#PCDATA)> 
<!ELEMENT vga (#PCDATA)> 

<!ATTLIST cpu brand CDATA #REQUIRED>
<!ATTLIST mb brand CDATA #REQUIRED>
<!ATTLIST hdd brand CDATA #IMPLIED>
<!ATTLIST vga brand CDATA #FIXED "NVIDIA">

=== rlawjddbs/jsp_prj/WebContent/xml0327/computer.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE computers SYSTEM "computer.dtd">
<computers>
	<computer>
		<cpu brand="인텔">i5</cpu>
		<mb brand="기가바이트"></mb>
		<ram>16Gbyte</ram>
		<ps>6team</ps>
		<hdd brand="WD">WD 1TByte</hdd>
		<odd>LG DVD</odd>
		<vga brand="NVIDIA">GTX-2080</vga>
	</computer>
</computers>
